@SUPABASE_PUBLIC_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1aWV5ZWh1b2R1d2V6cnFqemV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjg0ODk5ODgsImV4cCI6MjA0NDA2NTk4OH0.jFc_CIA8OVX6sVdIxpzvexOJPKMB5jqEpbvZNWNDlVk
@Token= eyJhbGciOiJIUzI1NiIsImtpZCI6IjBGbkkyL2huRUIzQjIvTWciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3J1aWV5ZWh1b2R1d2V6cnFqemV4LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJhNTY0MWY1Yi1hNDg5LTRjYjUtOTlhYS0yZDRiZmZlOWVmYzUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzI4NjQ2NzUwLCJpYXQiOjE3Mjg2NDMxNTAsImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnt9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzI4NjQzMTUwfV0sInNlc3Npb25faWQiOiI2N2YxNDAzMS03MTdlLTRjMDctYTI0MS0yY2RjMTBmYzY5YTgiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.umV_5YP4dVxoFIJPCvAI8uUan-4mStCUZCzQ6b_OiF4

### GET request to example server
POST https://ruieyehuoduwezrqjzex.supabase.co/auth/v1/token?grant_type=password
apiKey: {{SUPABASE_PUBLIC_KEY}}

{
  "email": "user@example.com",
  "password": "passipass"
}

###

GET http://localhost:8080/protected
Authorization: Bearer {{Token}}